package com.example.ecommerce.view.theme
import androidx.compose.ui.graphics.Color


val Dark = Color(0xFF4A4D4B)
val Black = Color(0xFF000000)
val White = Color(0xFFFFFFFF)
val grey_40 = Color(0xFF999999)
val grey_60 = Color(0xFF666666)
val grey_500 = Color(0xFF9E9E9E)
val grey_600 = Color(0xFF757575)
val darker_grey = Color(0xFFAAAAAA)
val grey = Color(0xFF979797)
val gold = Color(0xFFFFC107)
val orange = Color(0xFFFF5722)
val cyan = Color(0xFF26A69A)

val md_theme_light_primary = Color(0xFF0C84EC)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD4E3FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001C3A)
val md_theme_light_secondary = Color(0xFF0062A0)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD0E4FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001D34)
val md_theme_light_tertiary = Color(0xFF135FAC)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD5E3FF)
val md_theme_light_onTertiaryContainer = Color(0xFF001C3B)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF251A00)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF000000)
val md_theme_light_surfaceVariant = Color(0xFFE0E2EC)
val md_theme_light_onSurfaceVariant = Color(0xFF43474E)
val md_theme_light_outline = Color(0xFF0062B8)
val md_theme_light_inverseOnSurface = Color(0xFFFFEFD3)
val md_theme_light_inverseSurface = Color(0xFF3F2E00)
val md_theme_light_inversePrimary = Color(0xFFA5C8FF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF005FAE)
val md_theme_light_outlineVariant = Color(0xFFC3C6CF)
val md_theme_light_scrim = Color(0xFF000000)



